export const ADD_BOOK = "ADD_BOOK";
export const REMOVE_BOOK = "REMOVE_BOOK";
export const INCREMENT_BOOK_QUANTITY = "INCREMENT_BOOK_QUANTITY ";
export const DECREMENT_BOOK_QUANTITY = "DECREMENT_BOOK_QUANTITY";

